apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sdp.name" . }}-config
data:
{{- if .Values.config }}
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
{{- else }}
  config.yaml: |-
     dbmsServers:
      - name: dbms-dev-postgres
        type: postgresql
        fromSecret:
          namespace: default
          secret: dbms-dev-postgres-secret
{{- end }}