apiVersion: v1
kind: Service
metadata:
  name: "{{ template "sdp.name" . }}"
  labels:
{{ include "sdp.metadata_labels" . | indent 4 }}
  annotations:
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: {{ .Values.containerPort }}
  selector:
{{ include "sdp.selector_labels" . | indent 4 }}

