replicaCount: 1
containerPort: 8080

image:
  name: ecodia/simple-database-provisioner
  tag: v0.1.3
  pullPolicy: Always

serviceType: ClusterIP
ingress:
  enabled: false
  annotations: {}
  domain: "MUST_BE_SET"
  labels: {}

resources:
  limits:
    memory: 100Mi
    cpu: 100m
  requests:
    memory: 100Mi
    cpu: 100m

env: {}
nodeSelector: {}
tolerations: []
affinity: {}
