/*
 * Copyright (c) 2019 Ecodia GmbH & Co. KG <opensource@ecodia.de>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "simple-database-provisioner/pkg/apis/simpledatabaseprovisioner/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSimpleDatabaseInstances implements SimpleDatabaseInstanceInterface
type FakeSimpleDatabaseInstances struct {
	Fake *FakeSimpledatabaseprovisionerV1alpha1
	ns   string
}

var simpledatabaseinstancesResource = schema.GroupVersionResource{Group: "simpledatabaseprovisioner.k8s.ecodia.de", Version: "v1alpha1", Resource: "simpledatabaseinstances"}

var simpledatabaseinstancesKind = schema.GroupVersionKind{Group: "simpledatabaseprovisioner.k8s.ecodia.de", Version: "v1alpha1", Kind: "SimpleDatabaseInstance"}

// Get takes name of the simpleDatabaseInstance, and returns the corresponding simpleDatabaseInstance object, and an error if there is any.
func (c *FakeSimpleDatabaseInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(simpledatabaseinstancesResource, c.ns, name), &v1alpha1.SimpleDatabaseInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SimpleDatabaseInstance), err
}

// List takes label and field selectors, and returns the list of SimpleDatabaseInstances that match those selectors.
func (c *FakeSimpleDatabaseInstances) List(opts v1.ListOptions) (result *v1alpha1.SimpleDatabaseInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(simpledatabaseinstancesResource, simpledatabaseinstancesKind, c.ns, opts), &v1alpha1.SimpleDatabaseInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SimpleDatabaseInstanceList{ListMeta: obj.(*v1alpha1.SimpleDatabaseInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.SimpleDatabaseInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested simpleDatabaseInstances.
func (c *FakeSimpleDatabaseInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(simpledatabaseinstancesResource, c.ns, opts))

}

// Create takes the representation of a simpleDatabaseInstance and creates it.  Returns the server's representation of the simpleDatabaseInstance, and an error, if there is any.
func (c *FakeSimpleDatabaseInstances) Create(simpleDatabaseInstance *v1alpha1.SimpleDatabaseInstance) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(simpledatabaseinstancesResource, c.ns, simpleDatabaseInstance), &v1alpha1.SimpleDatabaseInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SimpleDatabaseInstance), err
}

// Update takes the representation of a simpleDatabaseInstance and updates it. Returns the server's representation of the simpleDatabaseInstance, and an error, if there is any.
func (c *FakeSimpleDatabaseInstances) Update(simpleDatabaseInstance *v1alpha1.SimpleDatabaseInstance) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(simpledatabaseinstancesResource, c.ns, simpleDatabaseInstance), &v1alpha1.SimpleDatabaseInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SimpleDatabaseInstance), err
}

// Delete takes name of the simpleDatabaseInstance and deletes it. Returns an error if one occurs.
func (c *FakeSimpleDatabaseInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(simpledatabaseinstancesResource, c.ns, name), &v1alpha1.SimpleDatabaseInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSimpleDatabaseInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(simpledatabaseinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SimpleDatabaseInstanceList{})
	return err
}

// Patch applies the patch and returns the patched simpleDatabaseInstance.
func (c *FakeSimpleDatabaseInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(simpledatabaseinstancesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SimpleDatabaseInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SimpleDatabaseInstance), err
}
