/*
 * Copyright (c) 2019 Ecodia GmbH & Co. KG <opensource@ecodia.de>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "simple-database-provisioner/pkg/apis/simpledatabaseprovisioner/v1alpha1"
	scheme "simple-database-provisioner/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SimpleDatabaseBindingsGetter has a method to return a SimpleDatabaseBindingInterface.
// A group's client should implement this interface.
type SimpleDatabaseBindingsGetter interface {
	SimpleDatabaseBindings(namespace string) SimpleDatabaseBindingInterface
}

// SimpleDatabaseBindingInterface has methods to work with SimpleDatabaseBinding resources.
type SimpleDatabaseBindingInterface interface {
	Create(*v1alpha1.SimpleDatabaseBinding) (*v1alpha1.SimpleDatabaseBinding, error)
	Update(*v1alpha1.SimpleDatabaseBinding) (*v1alpha1.SimpleDatabaseBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SimpleDatabaseBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.SimpleDatabaseBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SimpleDatabaseBinding, err error)
	SimpleDatabaseBindingExpansion
}

// simpleDatabaseBindings implements SimpleDatabaseBindingInterface
type simpleDatabaseBindings struct {
	client rest.Interface
	ns     string
}

// newSimpleDatabaseBindings returns a SimpleDatabaseBindings
func newSimpleDatabaseBindings(c *SimpledatabaseprovisionerV1alpha1Client, namespace string) *simpleDatabaseBindings {
	return &simpleDatabaseBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the simpleDatabaseBinding, and returns the corresponding simpleDatabaseBinding object, and an error if there is any.
func (c *simpleDatabaseBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.SimpleDatabaseBinding, err error) {
	result = &v1alpha1.SimpleDatabaseBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SimpleDatabaseBindings that match those selectors.
func (c *simpleDatabaseBindings) List(opts v1.ListOptions) (result *v1alpha1.SimpleDatabaseBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SimpleDatabaseBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested simpleDatabaseBindings.
func (c *simpleDatabaseBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a simpleDatabaseBinding and creates it.  Returns the server's representation of the simpleDatabaseBinding, and an error, if there is any.
func (c *simpleDatabaseBindings) Create(simpleDatabaseBinding *v1alpha1.SimpleDatabaseBinding) (result *v1alpha1.SimpleDatabaseBinding, err error) {
	result = &v1alpha1.SimpleDatabaseBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		Body(simpleDatabaseBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a simpleDatabaseBinding and updates it. Returns the server's representation of the simpleDatabaseBinding, and an error, if there is any.
func (c *simpleDatabaseBindings) Update(simpleDatabaseBinding *v1alpha1.SimpleDatabaseBinding) (result *v1alpha1.SimpleDatabaseBinding, err error) {
	result = &v1alpha1.SimpleDatabaseBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		Name(simpleDatabaseBinding.Name).
		Body(simpleDatabaseBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the simpleDatabaseBinding and deletes it. Returns an error if one occurs.
func (c *simpleDatabaseBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *simpleDatabaseBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched simpleDatabaseBinding.
func (c *simpleDatabaseBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SimpleDatabaseBinding, err error) {
	result = &v1alpha1.SimpleDatabaseBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("simpledatabasebindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
