/*
 * Copyright (c) 2019 Ecodia GmbH & Co. KG <opensource@ecodia.de>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "simple-database-provisioner/pkg/apis/simpledatabaseprovisioner/v1alpha1"
	scheme "simple-database-provisioner/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SimpleDatabaseInstancesGetter has a method to return a SimpleDatabaseInstanceInterface.
// A group's client should implement this interface.
type SimpleDatabaseInstancesGetter interface {
	SimpleDatabaseInstances(namespace string) SimpleDatabaseInstanceInterface
}

// SimpleDatabaseInstanceInterface has methods to work with SimpleDatabaseInstance resources.
type SimpleDatabaseInstanceInterface interface {
	Create(*v1alpha1.SimpleDatabaseInstance) (*v1alpha1.SimpleDatabaseInstance, error)
	Update(*v1alpha1.SimpleDatabaseInstance) (*v1alpha1.SimpleDatabaseInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SimpleDatabaseInstance, error)
	List(opts v1.ListOptions) (*v1alpha1.SimpleDatabaseInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SimpleDatabaseInstance, err error)
	SimpleDatabaseInstanceExpansion
}

// simpleDatabaseInstances implements SimpleDatabaseInstanceInterface
type simpleDatabaseInstances struct {
	client rest.Interface
	ns     string
}

// newSimpleDatabaseInstances returns a SimpleDatabaseInstances
func newSimpleDatabaseInstances(c *SimpledatabaseprovisionerV1alpha1Client, namespace string) *simpleDatabaseInstances {
	return &simpleDatabaseInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the simpleDatabaseInstance, and returns the corresponding simpleDatabaseInstance object, and an error if there is any.
func (c *simpleDatabaseInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	result = &v1alpha1.SimpleDatabaseInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SimpleDatabaseInstances that match those selectors.
func (c *simpleDatabaseInstances) List(opts v1.ListOptions) (result *v1alpha1.SimpleDatabaseInstanceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SimpleDatabaseInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested simpleDatabaseInstances.
func (c *simpleDatabaseInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a simpleDatabaseInstance and creates it.  Returns the server's representation of the simpleDatabaseInstance, and an error, if there is any.
func (c *simpleDatabaseInstances) Create(simpleDatabaseInstance *v1alpha1.SimpleDatabaseInstance) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	result = &v1alpha1.SimpleDatabaseInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		Body(simpleDatabaseInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a simpleDatabaseInstance and updates it. Returns the server's representation of the simpleDatabaseInstance, and an error, if there is any.
func (c *simpleDatabaseInstances) Update(simpleDatabaseInstance *v1alpha1.SimpleDatabaseInstance) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	result = &v1alpha1.SimpleDatabaseInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		Name(simpleDatabaseInstance.Name).
		Body(simpleDatabaseInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the simpleDatabaseInstance and deletes it. Returns an error if one occurs.
func (c *simpleDatabaseInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *simpleDatabaseInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched simpleDatabaseInstance.
func (c *simpleDatabaseInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SimpleDatabaseInstance, err error) {
	result = &v1alpha1.SimpleDatabaseInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("simpledatabaseinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
