// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import persistence "simple-database-provisioner/src/persistence"

import v1alpha1 "simple-database-provisioner/pkg/apis/simpledatabaseprovisioner/v1alpha1"

// DatabaseBindingService is an autogenerated mock type for the DatabaseBindingService type
type DatabaseBindingService struct {
	mock.Mock
}

// CreateDatabaseBinding provides a mock function with given fields: binding
func (_m *DatabaseBindingService) CreateDatabaseBinding(binding *v1alpha1.SimpleDatabaseBinding) error {
	ret := _m.Called(binding)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.SimpleDatabaseBinding) error); ok {
		r0 = rf(binding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDatabaseBinding provides a mock function with given fields: bindingId
func (_m *DatabaseBindingService) DeleteDatabaseBinding(bindingId persistence.NamespaceUniqueId) error {
	ret := _m.Called(bindingId)

	var r0 error
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId) error); ok {
		r0 = rf(bindingId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllDatabaseBindings provides a mock function with given fields:
func (_m *DatabaseBindingService) FindAllDatabaseBindings() []persistence.DatabaseBinding {
	ret := _m.Called()

	var r0 []persistence.DatabaseBinding
	if rf, ok := ret.Get(0).(func() []persistence.DatabaseBinding); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]persistence.DatabaseBinding)
		}
	}

	return r0
}

// FindBindingsByState provides a mock function with given fields: state
func (_m *DatabaseBindingService) FindBindingsByState(state persistence.ProvisioningState) []persistence.DatabaseBinding {
	ret := _m.Called(state)

	var r0 []persistence.DatabaseBinding
	if rf, ok := ret.Get(0).(func(persistence.ProvisioningState) []persistence.DatabaseBinding); ok {
		r0 = rf(state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]persistence.DatabaseBinding)
		}
	}

	return r0
}

// MarkDatabaseBindingForDeletion provides a mock function with given fields: bindingId
func (_m *DatabaseBindingService) MarkDatabaseBindingForDeletion(bindingId persistence.NamespaceUniqueId) error {
	ret := _m.Called(bindingId)

	var r0 error
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId) error); ok {
		r0 = rf(bindingId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDatabaseBindingState provides a mock function with given fields: bindingId, newState
func (_m *DatabaseBindingService) UpdateDatabaseBindingState(bindingId persistence.NamespaceUniqueId, newState persistence.State) error {
	ret := _m.Called(bindingId, newState)

	var r0 error
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId, persistence.State) error); ok {
		r0 = rf(bindingId, newState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
