// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import persistence "simple-database-provisioner/src/persistence"

import v1alpha1 "simple-database-provisioner/pkg/apis/simpledatabaseprovisioner/v1alpha1"

// DatabaseInstanceService is an autogenerated mock type for the DatabaseInstanceService type
type DatabaseInstanceService struct {
	mock.Mock
}

// CreateDatabaseInstance provides a mock function with given fields: instance
func (_m *DatabaseInstanceService) CreateDatabaseInstance(instance *v1alpha1.SimpleDatabaseInstance) error {
	ret := _m.Called(instance)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.SimpleDatabaseInstance) error); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDatabaseInstance provides a mock function with given fields: instanceId
func (_m *DatabaseInstanceService) DeleteDatabaseInstance(instanceId persistence.NamespaceUniqueId) error {
	ret := _m.Called(instanceId)

	var r0 error
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId) error); ok {
		r0 = rf(instanceId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllDatabaseInstances provides a mock function with given fields:
func (_m *DatabaseInstanceService) FindAllDatabaseInstances() []persistence.DatabaseInstance {
	ret := _m.Called()

	var r0 []persistence.DatabaseInstance
	if rf, ok := ret.Get(0).(func() []persistence.DatabaseInstance); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]persistence.DatabaseInstance)
		}
	}

	return r0
}

// FindDatabaseInstanceById provides a mock function with given fields: instanceId
func (_m *DatabaseInstanceService) FindDatabaseInstanceById(instanceId persistence.NamespaceUniqueId) (persistence.DatabaseInstance, error) {
	ret := _m.Called(instanceId)

	var r0 persistence.DatabaseInstance
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId) persistence.DatabaseInstance); ok {
		r0 = rf(instanceId)
	} else {
		r0 = ret.Get(0).(persistence.DatabaseInstance)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(persistence.NamespaceUniqueId) error); ok {
		r1 = rf(instanceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindInstancesByState provides a mock function with given fields: state
func (_m *DatabaseInstanceService) FindInstancesByState(state persistence.ProvisioningState) []persistence.DatabaseInstance {
	ret := _m.Called(state)

	var r0 []persistence.DatabaseInstance
	if rf, ok := ret.Get(0).(func(persistence.ProvisioningState) []persistence.DatabaseInstance); ok {
		r0 = rf(state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]persistence.DatabaseInstance)
		}
	}

	return r0
}

// MarkDatabaseInstanceForDeletion provides a mock function with given fields: instanceId
func (_m *DatabaseInstanceService) MarkDatabaseInstanceForDeletion(instanceId persistence.NamespaceUniqueId) error {
	ret := _m.Called(instanceId)

	var r0 error
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId) error); ok {
		r0 = rf(instanceId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDatabaseInstanceCredentials provides a mock function with given fields: instanceId, newCredentials
func (_m *DatabaseInstanceService) UpdateDatabaseInstanceCredentials(instanceId persistence.NamespaceUniqueId, newCredentials map[string][]byte) error {
	ret := _m.Called(instanceId, newCredentials)

	var r0 error
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId, map[string][]byte) error); ok {
		r0 = rf(instanceId, newCredentials)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDatabaseInstanceState provides a mock function with given fields: instanceId, newState
func (_m *DatabaseInstanceService) UpdateDatabaseInstanceState(instanceId persistence.NamespaceUniqueId, newState persistence.State) error {
	ret := _m.Called(instanceId, newState)

	var r0 error
	if rf, ok := ret.Get(0).(func(persistence.NamespaceUniqueId, persistence.State) error); ok {
		r0 = rf(instanceId, newState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
