// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CustomResourceDefinitionInstaller is an autogenerated mock type for the CustomResourceDefinitionInstaller type
type CustomResourceDefinitionInstaller struct {
	mock.Mock
}

// InstallCustomResourceDefinition provides a mock function with given fields: crdYaml
func (_m *CustomResourceDefinitionInstaller) InstallCustomResourceDefinition(crdYaml string) error {
	ret := _m.Called(crdYaml)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(crdYaml)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
