// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProvisioningEventProcessor is an autogenerated mock type for the ProvisioningEventProcessor type
type ProvisioningEventProcessor struct {
	mock.Mock
}

// ProcessEvents provides a mock function with given fields:
func (_m *ProvisioningEventProcessor) ProcessEvents() {
	_m.Called()
}
